spring.application.name=spring-Ngonde-Shadai-bradley
spring.profiles.active=dev
server.port=8081

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
